const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('kairozun', {
  onSystemMetrics: (cb) => ipcRenderer.on('system-metrics', (_e, data) => cb(data)),
  onSystemStatic: (cb) => ipcRenderer.on('system-static', (_e, data) => cb(data)),
  onSystemDisks: (cb) => ipcRenderer.on('system-disks', (_e, data) => cb(data)),
  onRobloxData: (cb) => ipcRenderer.on('roblox-data', (_e, data) => cb(data)),
  onScreenshotTaken: (cb) => ipcRenderer.on('screenshot-taken', (_e, filePath) => cb(filePath)),
  onStartRecording: (cb) => ipcRenderer.on('start-recording', (_e, data) => cb(data)),
  onStopRecording: (cb) => ipcRenderer.on('stop-recording', () => cb()),
  saveRecording: (buffer) => ipcRenderer.send('save-recording', buffer),
  startRecordingFile: () => ipcRenderer.send('recording-start-file'),
  sendRecordingChunk: (buffer) => ipcRenderer.send('recording-chunk', buffer),
  endRecordingFile: () => ipcRenderer.send('recording-end-file'),
  recordingState: (recording) => ipcRenderer.send('recording-state', recording),
  onApplySettings: (cb) => ipcRenderer.on('apply-settings', (_e, s) => cb(s)),
  updateSettings: (settings) => ipcRenderer.send('update-settings', settings),
  getSettings: () => ipcRenderer.sendSync('get-settings'),
  getGameHistory: () => ipcRenderer.sendSync('get-game-history'),
  deleteHistoryEntry: (idx) => ipcRenderer.send('delete-history-entry', idx),
  lookupPlayer: (username) => ipcRenderer.invoke('lookup-player', username),
  closeSettings: () => ipcRenderer.send('close-settings'),
  minimizeSettings: () => ipcRenderer.send('minimize-settings'),
  setOverlayMouse: (ignore) => ipcRenderer.send('overlay-mouse', ignore),
  setHotkey: (action, accelerator) => ipcRenderer.send('set-hotkey', { action, accelerator }),
  setCaptureMode: (visible) => ipcRenderer.send('set-capture-mode', visible),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  openEditor: (data) => ipcRenderer.send('open-editor', data),
  getScreenshots: () => ipcRenderer.invoke('get-screenshots'),
  readScreenshot: (filePath) => ipcRenderer.invoke('read-screenshot', filePath),
  readScreenshotThumb: (filePath) => ipcRenderer.invoke('read-screenshot-thumb', filePath),
  saveEditedScreenshot: (data) => ipcRenderer.invoke('save-edited-screenshot', data),
  deleteScreenshot: (filePath) => ipcRenderer.invoke('delete-screenshot', filePath),
  openScreenshotsFolder: () => ipcRenderer.send('open-screenshots-folder'),
  openCollage: (data) => ipcRenderer.send('open-collage', data),
});
